spring:
  #数据源配置
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: 00000
  password: 00000..
  url: jdbc:mysql://0000:3306/mysql?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #redis配置
 redis:
  host: 0000
  database: 0
  port: 6379
  password: 0000..
  jedis:
   pool:
    max-active: 8
    max-wait: -1ms
    max-idle: 8
    min-idle: 0
  timeout: 20000ms
wxinfo:
  getSessionIdUrl: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
  appId: 00000
  secret: 00000

